#!/bin/sh

# run from root of project

PASSED=$(cat elfutils/test-log | grep "# PASS:" | awk '{ print $3 }')
PREV=$(cat testing/passed)
if [ $PASSED -gt $PREV ]
then
        echo passed tests went from $PREV to $PASSED
        echo $PASSED > testing/passed
elif [ $PASSED -lt $PREV ]
        echo passed tests ($PASSED) went down from $PREV
        exit 1
fi
