name: elfutils-tests
on:
  workflow_dispatch:
  pull_request:

jobs:
  elfutils-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Dependencies
        run: sudo apt install libelf-dev autotools

      - uses: actions/checkout@v2
      - run: git clone git://sourceware.org/git/elfutils.git

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      
      - run: zig build
