name: elfutils-tests
on:
  workflow_dispatch:
  pull_request:

jobs:
  elfutils-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - uses: actions/checkout@v2
      - run: git clone git://sourceware.org/git/elfutils.git
      
