name: elfutils-tests
on:
  workflow_dispatch:
  pull_request:

jobs:
  elfutils-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential libelf-dev autopoint

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - uses: actions/checkout@v2
      - run: git clone git://sourceware.org/git/elfutils.git
      
      - run: zig build

      - name: Configure elfutils
        working-directory: elfutils
        run: |
          autoreconf -i -f
          ./configure --enable-maintainer-mode --enable-libdebuginfod=dummy

      - name: Toss in our stuff
        run: |
          cp testing/libelf-Makefile elfutils/libelf/Makefile
          cp zig-out/lib/* elfutils/libelf

      - name: Build elfutils
        working-directory: elfutils
        run: make

